-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_forms" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "handle" TEXT not null,
  "status" TEXT CHECK ("status" IN ('draft', 'active', 'closed')) default 'draft',
  "settings" TEXT,
  "site_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_forms" ("id", "name", "handle", "status", "settings", "site_id", "created_at", "updated_at", "uuid") SELECT "id", "name", "handle", "status", "settings", "site_id", "created_at", "updated_at", "uuid" FROM "forms";
DROP TABLE "forms";
ALTER TABLE "_qb_tmp_forms" RENAME TO "forms";
CREATE UNIQUE INDEX IF NOT EXISTS "forms_site_handle_unique" ON "forms" ("site_id", "handle");
CREATE UNIQUE INDEX IF NOT EXISTS "forms_uuid_unique" ON "forms" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_form_submissions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "data" TEXT not null,
  "email" TEXT,
  "name" TEXT,
  "status" TEXT CHECK ("status" IN ('pending_payment', 'complete', 'spam')) default 'complete',
  "amount_cents" INTEGER,
  "payment_intent_id" TEXT,
  "ip" TEXT,
  "submitted_at" TEXT,
  "form_id" INTEGER REFERENCES "forms"("id"),
  "site_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_form_submissions" ("id", "data", "email", "name", "status", "amount_cents", "payment_intent_id", "ip", "submitted_at", "form_id", "site_id", "created_at", "updated_at", "uuid") SELECT "id", "data", "email", "name", "status", "amount_cents", "payment_intent_id", "ip", "submitted_at", "form_id", "site_id", "created_at", "updated_at", "uuid" FROM "form_submissions";
DROP TABLE "form_submissions";
ALTER TABLE "_qb_tmp_form_submissions" RENAME TO "form_submissions";
CREATE UNIQUE INDEX IF NOT EXISTS "form_submissions_uuid_unique" ON "form_submissions" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
